Revert 17176 - test suite regression
Two Combinator tests fail with this changeset:

{{{
===============================================================================
[ERROR]: combinator.test.test_branchmgr.BranchManagerChangeBranchTests.test_mergeTrunk

Traceback (most recent call last):
  File "/var/lib/buildbot/divmod-bigdogvm1/q-linux/build/Divmod/Combinator/combinator/test/test_branchmgr.py", line 534, in test_mergeTrunk
    self.assertEqual(err.args, ())
exceptions.AttributeError: InvalidBranch instance has no attribute args
===============================================================================
[ERROR]: combinator.test.test_branchmgr.FakeBranchManagerChangeBranchTests.test_mergeTrunk

Traceback (most recent call last):
  File "/var/lib/buildbot/divmod-bigdogvm1/q-linux/build/Divmod/Combinator/combinator/test/test_branchmgr.py", line 534, in test_mergeTrunk
    self.assertEqual(err.args, ())
exceptions.AttributeError: InvalidBranch instance has no attribute args
===============================================================================
}}}

Reopens #2791